server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never
    include-exception: false    

spring:
  data:
    mongodb:
      database: ecommerce
      host: localhost
      port: 27017      
      auto-index-creation: true

